Match User vpn-transit
    AuthenticationMethods publickey
    PasswordAuthentication no
    PermitTunnel point-to-point
    AllowTcpForwarding no
    AllowStreamLocalForwarding no
    X11Forwarding no
    PermitTTY no
Match all
