# Private SOCKS endpoint. Reachable only through the RU-DE WireGuard channel.
logoutput: syslog
internal: 10.212.0.2 port = 1080
external: ens3
socksmethod: none
clientmethod: none
user.privileged: root
user.unprivileged: nobody

client pass {
    from: 10.212.0.1/32 to: 0.0.0.0/0
    log: error
}
socks pass {
    from: 10.212.0.1/32 to: 0.0.0.0/0
    command: connect
    protocol: tcp
    log: error
}
